preset: laravel

enabled:
  - strict
  - align_double_arrow
  - dir_constant
  - linebreak_after_opening_tag
  - no_short_echo_tag
  - non_printable_character
  - ordered_class_elements
  - phpdoc_add_missing_param_annotation
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - phpdoc_order
  - phpdoc_separation
  - phpdoc_return_self_reference
  - align_equals
  - concat_with_spaces
  - length_ordered_imports
  - const_visibility_required
  - native_constant_invocation
  - php_unit_construct
  - php_unit_set_up_tear_down_visibility
  - php_unit_strict
  - php_unit_test_class_requires_covers
  - php_unit_expectation

disabled:
  - unalign_equals
  - concat_without_spaces
  - declare_equal_normalize
  - alpha_ordered_imports
  - single_class_element_per_statement
